// Filename: public/functions.js

export function generatePrompt(){
	const arr = [
		"Identify 5 Things You’re Grateful For:", 
        "Talk About Your Day:",
        "Describe a Goal:",
        "List and Describe Your Emotions:",
        "Write About How Different You Were 5 Years Ago", 
        "Write a Letter to Your Body",
        "Describe the Best Compliment You’ve Ever Gotten",
        "Write About How You’d Describe Yourself to a Stranger",
        "Write a Message for Yourself on Bad Days",
        "What do you like most about your personality?",
        "Whom do you trust the most? Why?",
        "What are your strengths in friendships or relationships (e.g., kindness, empathy)?",
        "What do you most want for your children (or future children)?",
        "How do you draw strength from loved ones?",
        "What boundaries could you set in your relationships to safeguard your own wellbeing?",
        "What do you value most in your relationships, with romantic partners, friends or family?",
        "What five traits do you value most in potential partners?",
        "Write a love letter to yourself.",
        "What are three important lessons have you learned from previous relationships?",
        "What are three things that are working well in your current relationship?",
        "What are three things that could be better in your current relationship?",
        "How do you show compassion to others? How can you extend that same compassion to yourself?",
        "I get anxious when _____________.",
        "When do you feel most happy?",
        "What was one moment of joy or beauty you experienced today?",
        "Describe a place where you feel most relaxed and peaceful.",
        "Write a letter of forgiveness to yourself.",
        "What or who motivates you the most? Why?",
        "Share an act of selflessness or kindness you did for someone. How did it feel to do this?",
        "What was your favorite story or book as a child? Why did you like it so much?",
        "What’s the most rewarding part of your work?",
        "What’s your favorite part of your day?",
        "Which parts of your daily life cause the most stress or frustration? How do you cope with them?",
        "Describe your favorite memory.",
        "Write down all your coping mechanisms. Evaluate the ones that are most helpful and the ones that are the most detrimental.",
        "Write a letter to your future self.",
        "Recount the last random moment that made you smile.",
        "What are your favorite books? Why are they your favorite? Write about them.",
        "Write down 5 things that make you incredibly happy and describe why they make you feel this way.",
        "What do you fear the most? Why? Is your fear rational?",
        "What qualities about yourself do you love the most?",
        "In the next year, what are 5 improvements you would like to make regarding your life?",
        "Write about the people in your life that make you feel the most “at ease” and what they do to make you feel that way.",
        "Write about a difficult memory and the coping mechanisms you used at the time. Would you change the way you dealt? How?",
        "Write about the last time you cried. What caused you to cry?",
        "Write about the last time you laughed really hard. What was so funny?",
        "Write a letter to one of your parents – even if you don’t actually give it to them.",
        "What has your anxiety taught you about yourself?",
        "Write down a list of ‘regrets’.",
        "In detail, describe a perfect day.",
        "Write a letter to a person who has negatively impacted you."
	]
	    return arr[Math.floor(Math.random() * 49)];

}
